"""init base tables

Revision ID: 48260491c2b0
Revises: 
Create Date: 2025-10-29 09:18:35.945011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48260491c2b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('cnp', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('emp_id'),
    sa.UniqueConstraint('cnp'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bonuses',
    sa.Column('bonus_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bonus_id')
    )
    op.create_table('vacations',
    sa.Column('vac_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vac_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacations')
    op.drop_table('bonuses')
    op.drop_table('employees')
    # ### end Alembic commands ###
